apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: yinan9751/moon-ladder:572ab2557eeeacc3f88258db84d97c613ff3e608
        name: helloworld
        ports:
        - containerPort: 8081


